### PR TITLE
Issue #114, Ensure minimum unit for LeaveApplication#hours is at least an hour

### PR DESCRIPTION
**Pull request by YushengLi**
- Ensure minimum unit for LeaveApplication#hours is at least an hour
- Rewrite spec for this situation

### CODE REVIEW

**Comment by Maxwell-Alexius** [comment]
LeaveApplicationController#create 那邊的 `if object.save!` 的驚嘆號要拔掉 除此之外 LGTM

**Comment by YushengLi** [comment]
@Maxwell-Alexius LeavaApplication Controller 並不在這次 Review 的範圍喔。

**Comment by Maxwell-Alexius** [comment]
@YushengLi  了解！ LGTM

**Comment by YushengLi** [comment]
By the way 下次可以直接使用 Line comments 來 Review 會比較方便喔

**Pull request merged**
